### ISSUE TITLE
Crash when harvesting Immersive Engineering hemp

### ISSUE THREAD

**Issue by BookerCatch** [lunekiska/Scythd#1]
I didn't do any testing at all, but the crash report points to the BYG mod, which should not be a required dependency. Thanks for the awesome mod!

https://pastebin.com/fsX3JKZ5

**Comment by lunekiska** [comment]
I' ll work on it now and publish the fix update soon. I know where may be the problem :>

**Comment by lunekiska** [comment]
Ok, Fixed
I also added possibility to  harvest IE's  hemp
Btw bug was appearing because of my bad making code using BYG blocks without mod installed

So now I'm closing the issue
